meta_product_name: "Care Key"
meta_title: "Care Key - Where self-care is the key to level up!"
meta_description: "Care Key is a self care routine builidng application that makes building good routines fun. Come join us on Care Key to level up your life."
meta_image: "app/assets/images/icons/provisional_logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
